branches:
  only:
  - pelican
language: python
python:
- '3.5'
before_install:
- openssl aes-256-cbc -K $encrypted_36812bacabfa_key -iv $encrypted_36812bacabfa_iv -in publish-key.enc -out ~/.ssh/publish-key -d
- chmod u=rw,og= ~/.ssh/publish-key
- echo "Host github.com" >> ~/.ssh/config
- echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
- git remote set-url origin git@github.com:rtancman/rtancman.github.io.git
- git fetch origin -f master:master
install:
- git submodule update --remote --merge
- pip install --upgrade pip
- pip install -r requirements.txt
script:
- make github